CREATE TABLE [GCMProdStkAndContract](
	[GCMProdStkAndContractID] varchar(50) NOT NULL COLLATE NOCASE,
	[ProductSerialNumber] varchar(50) NOT NULL COLLATE NOCASE,
	[OrganizationCode] varchar(50) COLLATE NOCASE,
	[ProductID] varchar(50) COLLATE NOCASE,
	[Type] varchar(50) COLLATE NOCASE,
	[OldSubTeamCode] varchar(50) COLLATE NOCASE,
	[OldTeamCode] varchar(50) COLLATE NOCASE,
	[NewSubTeamCode] varchar(50) COLLATE NOCASE,
	[NewTeamCode] varchar(50) COLLATE NOCASE,
	[ProdStkStatus] varchar(50) COLLATE NOCASE,
	[ImportDate] datetime,
	[ScanByTeam] varchar(50) COLLATE NOCASE,
	[ScanDate] datetime,
	[ProdStkCreateBy] varchar(50) COLLATE NOCASE,
	[ProdStkCreateDate] datetime,
	[ProdStkUserID] varchar(50) COLLATE NOCASE,
	[ProdStkUserName] varchar(50) COLLATE NOCASE,
	[ProdStkDeviceID] varchar COLLATE NOCASE,
	[RefNo] varchar(50) COLLATE NOCASE,
	[ContractUserID] varchar(50) COLLATE NOCASE,
	[ContractUserName] varchar(50) COLLATE NOCASE,
	[ContractDeviceID] varchar COLLATE NOCASE,
	[CreateDate] datetime,
	[CreateBy] varchar(50) COLLATE NOCASE,
	[LastUpdateDate] datetime,
	[LastUpdateBy] varchar(50) COLLATE NOCASE,
	[SyncedDate] datetime,
	PRIMARY KEY ([GCMProdStkAndContractID])
 );
